language: php
addons:
  chrome: stable
services:
  - mysql
php:
  - 7.1
  - 7.2
  - 7.3
env:
  global:
    - CHROME_BINARY=google-chrome-stable
    - COMPOSER_NO_INTERACTION=1
    - DB_USERNAME=root
    - DB_PASSWORD=root
  matrix:
    - LARAVEL_VERSION=5.5
    - LARAVEL_VERSION=master
script:
  - make test
