language: php
addons:
  chrome: stable
services:
  - mysql
php:
  - 7.1
  - 7.2
  - 7.3
env:
  global:
    - CHROME_BINARY=google-chrome-stable
    - COMPOSER_NO_INTERACTION=1
    - DB_USERNAME=e2e
    - DB_PASSWORD=e2e
  matrix:
    - LARAVEL_VERSION=5.5
    - LARAVEL_VERSION=master
before_install:
  - mysql -u root --password="" < test/e2e.sql
script:
  - make test
